python /its1/GB_BT2/jianzuoyi/biosoft/bionano/tools/pipeline/1.0/Pipeline/1.0/pipelineCL.py \
-T 24 \
-f 0.2 \
-i 5 \
-y \
-V 0 \
-m \
-b /its1/GB_BT2/jianzuoyi/workspace/Pepper/Assembly/Bionano/pepper.merged.filter.SNR.len.bnx \
-l /its1/GB_BT2/jianzuoyi/workspace/Pepper/Assembly/Bionano/denovoIII \
-t /its1/GB_BT2/jianzuoyi/biosoft/bionano/tools/pipeline/1.0/RefAligner/1.0/ \
-a /its1/GB_BT2/jianzuoyi/biosoft/bionano/tools/pipeline/1.0/RefAligner/1.0/optArguments_haplotype_saphyr.xml \
-r /its1/GB_BT2/jianzuoyi/workspace/Pepper/Assembly/Bionano/denovoI/contigs/exp_mrg0/EXP_MRG0A.cmap
